### PR TITLE
Normal user dashboard UI & Status change notification message

### LINKED ISSUE #686: Admin dashboard UI shows for non-admin users
## Expected Behavior
Users with no admin-level permission should not see the website statistics (editing roles or users)

## Current Behavior
Users who are missing these permissions in their role are able to see the admin dashboard

## Possible Solution
Adjust which users see the roles

## Steps to Reproduce

1. Log in as user without a roles. or users. permission

# Bug Submission Checklist
- [x] Replication steps

### PR DESCRIPTION
**Pull request by Alex-Hayeur**
##### _What existing problem does the pull request solve?_

Makes it so that users with "booking.create" permission no longer see the admin dashboard.
Fixes the english of the email notification for a status change to better suit the new statuses

##### _Demonstrate the code is solid. </br> Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI._

Capture
This is the new dashboard for users without a "role" or "user" permission

##### _List all issues this PR resolves_
- closes #686 and #687 
##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### Sub-tasks Checklist
- [x] UI Implementation
- [x] UI Test
- [x] Backend Implementation
- [x] Backend Tests
- [x] Integration Tests

### CODE REVIEW

**Review by EvanDime — APPROVED** [review]

File: app/Notifications/BookingUpdateNotification.php [hunk 1]
```diff
@@ -45,7 +45,8 @@ public function via($notifiable)
     public function toMail($notifiable)
     {
         return (new MailMessage)
-                    ->line('Your booking has been '.$this->booking->status)
+                    ->line('Your booking status has been updated!')
+                    ->line('Your booking is now: '.$this->booking->status)
```
Comment (danseremet) [inline app/Notifications/BookingUpdateNotification.php:49]: nice change for proper english! :smile:

File: resources/js/Pages/Dashboard.vue [hunk 2]
```diff
@@ -16,8 +16,10 @@
                   <DashboardMetrics :metrics="users" />
                   </h3>
                 </div>
-                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-8 items-center" v-else>
-                  <h3>Welcome!</h3>
+                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-8 items-center content-center" v-else>
+                  <jet-application-mark class="block h-40 w-auto"/>
+                  <h2>Welcome to the CSU Booking application!</h2>
+                  <h3>If you are unable to see the pages you need in the Navbar above, please contact  <a class="text-yellow-300" href="mailto:it@csu.qc.ca">it@csu.qc.ca</a></h3>
```
Comment (danseremet) [inline resources/js/Pages/Dashboard.vue:22]: good to let the user know what is happening in this case! :+1:

**Review by danseremet — APPROVED** [review]
Nice, LGTM! :100:
