### PR TITLE
fix 408 bug

### LINKED ISSUE #408: Create room Bookable window does not save.
## Expected Behavior
When you create a room, you should be able to input max and minimum number of days and have them be saved in the DB.
## Current Behavior
Filling in numbers for these fields does nothing and null values are put in the DB. 
## Possible Solution
Fix the create room form. 
## Steps to Reproduce

Screen Shot 2021-01-28 at 4 18 07 PM
Screen Shot 2021-01-28 at 4 18 20 PM

1. Create a room with online form. 
2. Look at room information once complete. 
3. notice lack of max and min days to book.

## Context (Environment)

# Bug Submission Checklist
- [x] Replication steps
- [x] Screenshots
- [x] Tagged commits fixing the bug for traceability
- [x] Tagged commits updating tests to cover the reported bug

### PR DESCRIPTION
**Pull request by EvanDime**
##### _What existing problem does the pull request solve?_
Solve bug #408 where creating a room didn't save the min/max day values. 

##### _Demonstrate the code is solid. </br> Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI._
Add check in feature test to check and see if max/min day is in the DB. 
##### _List all issues this PR resolves_
- closes #408

##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### Sub-tasks Checklist
- [x] UI Implementation
- [x] UI Test
- [x] Backend Implementation
- [x] Backend Tests
- [x] Integration Tests
- [x] System Tests
- [x] Documentation

### CODE REVIEW

**Review by Alex-Hayeur — APPROVED** [review]

File: app/Http/Controllers/RoomController.php [hunk 1]
```diff
@@ -108,7 +107,8 @@ public function store(Request $request)
                 'sale_for_profit' => $request->sale_for_profit,
                 'fundraiser' => $request->fundraiser,
             ],
-
+            'min_days_advance' => $request->min_days_advance ?? 0,
+            'max_days_advance' => $request->max_days_advance ?? 30,
```
Comment (WindOfRussia) [inline app/Http/Controllers/RoomController.php:111]: reminder to move these into config file once we create an app config

**Review by WindOfRussia — APPROVED** [review]
good catch, I was wondering why db columns were always null
