### PR TITLE
fix(#159): Fix sonarcloud codesmells & bugs

### LINKED ISSUE #159: Address project code smells & bugs
*Do not assign a story-point value to this task*

### What needs to be done
At the time of creating this ticket, there are 9 code smells and 1 bug reported by Sonarcloud. The task is to investigate each one and either fix it, or close the issue with a justification. For example, if a smell/bug is a false-positive (reporting something that isn't there/doesn't make sense), use the "resolve as false positive" button in Sonarcloud and justify why in this ticket. 

Bugs report: https://sonarcloud.io/project/issues?id=CSU-Booking-Platform_application&resolved=false&types=BUG
Smells report: https://sonarcloud.io/project/issues?id=CSU-Booking-Platform_application&resolved=false&types=CODE_SMELL

### Out of scope
Any code modifications unrelated to fixing code smells or bugs

### PR DESCRIPTION
**Pull request by alecadub**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

Fix sonar cloud code smells and bugs

### Test plan (required)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

image

### Closing issues
List all issues this PR resolves.
- `closes #159 ` 

### Pre-Merge checklist 
Complete these items before requesting reviews
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions 

### Sub-tasks Checklist
- [ ] UI Implementation
- [ ] UI Test
- [ ] Backend Implementation
- [ ] Backend Tests
- [ ] Integration Tests
- [ ] System Tests

### CODE REVIEW

File: app/Providers/RouteServiceProvider.php [hunk 1]
```diff
@@ -54,7 +54,7 @@ public function boot()
      */
     protected function configureRateLimiting()
     {
-        RateLimiter::for('api', function (Request $request) {
+        RateLimiter::for('api', function () {
```
Comment (EvanDime) [inline app/Providers/RouteServiceProvider.php:57]: Does this not make it worse? The request isn't used in the function.

File: routes/web.php [hunk 2]
```diff
@@ -15,7 +15,7 @@
 */
 
 Route::get('/', function () {
-    return view('welcome');
+    return redirect()->route('login');
```
[the remark this answers is not in the document]
Comment (alecadub) [reply routes/web.php:18]: I didn't see any in the mockups! I deleted the unused Laravel generated code for the _welcome_ page, but if we are going to use a homepage, we could leave it blank for now

File: app/Http/Middleware/HandleInertiaRequests.php [hunk 3]
```diff
@@ -7,18 +7,6 @@
...
-     *
-     * @see https://inertiajs.com/asset-versioning
-     * @param  \Illuminate\Http\Request  $request
-     * @return string|null
-     */
-    public function version(Request $request)
-    {
-        return parent::version($request);
-    }
-
```
[the remark this answers is not in the document]
Comment (alecadub) [reply app/Http/Middleware/HandleInertiaRequests.php:21]: Good point ! I didn't see any value in the function, but maybe I'm missing something, maybe @WindOfRussia can help us out since he had experience with Inertia

File: app/Providers/RouteServiceProvider.php (hunk 1 above)
Comment (alecadub) [reply app/Providers/RouteServiceProvider.php:57]: I removed it since it isn't used in the function, not sure how it make it worse but maybe I'm missing something

**Comment by alexstojda** [comment]
@WindOfRussia could you have a look at this, please? Your expertise is needed.

File: app/Http/Middleware/HandleInertiaRequests.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (alexstojda) [reply app/Http/Middleware/HandleInertiaRequests.php:21]: Yes, this is a required function let's keep the function and mark any issues in Sonar as a False-positive

File: app/Providers/RouteServiceProvider.php (hunk 1 above)
Comment (alexstojda) [reply app/Providers/RouteServiceProvider.php:57]: @WindOfRussia Does the function need to have the parameter?

File: routes/web.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (alexstojda) [reply routes/web.php:18]: We can remove the default welcome page. It's causing the majority of the code smells anyway.

File: app/Http/Middleware/HandleInertiaRequests.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (WindOfRussia) [reply app/Http/Middleware/HandleInertiaRequests.php:21]: This is a stub, even if it looks off, better to keep it

File: app/Providers/RouteServiceProvider.php (hunk 1 above)
Comment (WindOfRussia) [reply app/Providers/RouteServiceProvider.php:57]: nah, the parameter is only there by default to remind users they can customize the rate limiter based on some information from the request. hypothetical example: user-tier free is limiter to 10 api requests a second but paid users of the said system can have more

File: app/Http/Controllers/RoleController.php [hunk 4]
```diff
@@ -8,6 +8,9 @@
 
 class RoleController extends Controller
 {
+
+    private string $redirectTo = 'roles.index';
```
Comment (WindOfRussia) [inline app/Http/Controllers/RoleController.php:12]: Not a fan of this refactor. I understand the logic, but its inpractical in laravel.

@alexstojda can we make the repeated string check higher or mark it as a false positive?

File: app/Http/Controllers/UserController.php [hunk 5]
```diff
@@ -14,6 +14,8 @@ class UserController extends Controller
 {
     use PasswordValidationRules;
 
+    private string $userMaxColumnSize = 'max:255';
```
Comment (WindOfRussia) [inline app/Http/Controllers/UserController.php:17]: same comment as with the redirectTo @alexstojda

File: app/Http/Controllers/RoleController.php (hunk 4 above)
Comment (alexstojda) [reply app/Http/Controllers/RoleController.php:12]: @alecadub You can mark it as a false positive in Sonarcloud and undo the change

File: app/Http/Controllers/UserController.php (hunk 5 above)
Comment (alexstojda) [reply app/Http/Controllers/UserController.php:17]: @alecadub You can mark it as a false positive in Sonarcloud and undo the change

File: app/Http/Middleware/HandleInertiaRequests.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (alexstojda) [reply app/Http/Middleware/HandleInertiaRequests.php:21]: @alecadub You can mark it as a false positive in Sonarcloud and undo the change

**Review by alexstojda — APPROVED** [review]
LGTM

**Review by Alex-Hayeur — APPROVED** [review]
We'll need to discuss which page would function best as the homepage, but I agree with removing the welcome page.
